export interface Order{
    sellerStore?: string,
    shippingMethod?: string,
    externalOrderNumber?: number,
    buyerFullName?: string,
    buyerPhoneNumber?: string,
    buyerEmail?: string,
    shippingAddress?: string,
    shippingCity?: string,
    shippingRegion?: string,
    shippingCountry?: string,
    date?: string,
    internalOrderNumber?: number,
    lineItems?: object[],
    packPromiseMin?: number,
    packPromiseMax?:number,
    shipPromiseMin?:number,
    shipPromiseMax?:number,
    deliveryPromiseMin?:number,
    deliveryOromiseMax?:number,
    readyPickupPromiseMin?:number,
    readyPickupPromiseMax?:number,
  }